// <auto-generated />
using System;
using LicenseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenseService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813143619_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("license")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenseService.Entities.License", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("customer_site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expire_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC') + INTERVAL '1 year'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("license")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("license_type")
                        .HasColumnType("integer");

                    b.Property<string>("machine_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("sign_key_guid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("sign_key_guid");

                    b.ToTable("license", "license");
                });

            modelBuilder.Entity("LicenseService.Entities.SignKeyAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("expire_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC') + INTERVAL '1 year'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("sign_priv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("sign_pub")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.ToTable("sign_key", "license");
                });

            modelBuilder.Entity("LicenseService.Entities.License", b =>
                {
                    b.HasOne("LicenseService.Entities.SignKeyAudit", "sign_key")
                        .WithMany("licenses")
                        .HasForeignKey("sign_key_guid")
                        .HasPrincipalKey("guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sign_key");
                });

            modelBuilder.Entity("LicenseService.Entities.SignKeyAudit", b =>
                {
                    b.Navigation("licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
